CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

CREATE TABLE IF NOT EXISTS USUARIOS (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS LIBROS (
    id_libro VARCHAR(255) PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    escritor VARCHAR(255) NOT NULL,
    genero VARCHAR(255) NOT NULL,
    anio INT NOT NULL,
    premisa TEXT,
    stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    libro_id VARCHAR(255) NOT NULL,
    fecha_reserva DATE NOT NULL,
    fecha_devolucion DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_reserva_user FOREIGN KEY (user_id) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    CONSTRAINT fk_reserva_libro FOREIGN KEY (libro_id) REFERENCES LIBROS(id_libro) ON DELETE CASCADE
);
