server.port=8080

# Azure Functions base URLs
azure.functions.users.url=https://cloudnative-duoavengers-gvexfnfvaybbedaz.brazilsouth-01.azurewebsites.net/api/users
azure.functions.bookloans.url=https://cloudnative-duoavengers-gvexfnfvaybbedaz.brazilsouth-01.azurewebsites.net/api/reservas

