server.port=8080

# Azure Functions base URLs
azure.functions.users.url=http://localhost:7071/api/users
azure.functions.bookloans.url=http://localhost:7071/api/loans
azure.functions.example.url=https://cloudnative-duoavengers-gvexfnfvaybbedaz.brazilsouth-01.azurewebsites.net/api/HttpExample
